### ISSUE TITLE
Merging master into new notebook branch 

### ISSUE THREAD

**Issue by JeanBilheux** [neutronimaging/ToFImaging#93]

**Comment by JeanBilheux** [comment]
Normalization fails 
```
Traceback (most recent call last):
  File "/Users/j35/git/ToFImaging/JupyterNotebooks/code/decorators.py", line 14, in wrapper
    function(self)
  File "/Users/j35/git/ToFImaging/JupyterNotebooks/code/fit_interface.py", line 167, in prepare_data_button_clicked
    o_event.prepare_data()
  File "/Users/j35/git/ToFImaging/JupyterNotebooks/code/prepare_data.py", line 69, in prepare_data
    self.calculate_mask()
  File "/Users/j35/git/ToFImaging/JupyterNotebooks/code/prepare_data.py", line 19, in calculate_mask
    [_, height, width] = np.shape(self.parent.normalize_projections)
AttributeError: 'Interface' object has no attribute 'normalize_projections'
```
